# Generated by Django 4.2.1 on 2023-05-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ExerciseID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Sets', models.IntegerField()),
                ('Reps', models.IntegerField()),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecords',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('Exercise', models.CharField(max_length=50)),
                ('Weight', models.IntegerField()),
                ('Reps', models.IntegerField()),
                ('Date', models.DateField()),
                ('BodyWeight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('WorkoutID', models.AutoField(primary_key=True, serialize=False)),
                ('Split', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Exercises', models.ManyToManyField(to='WorkoutApp.exercise')),
            ],
        ),
    ]
