# Generated by Django 4.2.1 on 2023-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('muscle', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecords',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('Exercise', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('Reps', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('BodyWeight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('WorkoutID', models.AutoField(primary_key=True, serialize=False)),
                ('Split', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Exercises', models.CharField(max_length=300)),
                ('Rating', models.CharField(max_length=50)),
            ],
        ),
    ]
