# Generated by Django 4.2.1 on 2023-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('MuscleID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Exercises', models.CharField(max_length=200)),
            ],
        ),
    ]
